### ISSUE TITLE
Incorrect handle positioning noUiSlider 14.x

### ISSUE THREAD

**Issue by StevenVerbiest** [surveyjs/widgets#176] opened 2020-04-27 12:22 UTC
Example can be found at https://stackblitz.com/edit/surveyjs-widgets-react-dblzzt?file=index.js

The handle is shifted to the right.

I used https://stackblitz.com/edit/surveyjs-widgets-react?file=index.js as a starting point and just updated some dependencies.

**Comment by tsv2013** [comment] 2020-04-27 13:37
It's a bug. We'll fix it.

**Comment by tsv2013** [comment] 2020-04-28 11:32
I've created a plunker sample with nouislider based upon our example (https://surveyjs.io/Examples/Library?id=custom-widget-nouislider&platform=Reactjs&theme=modern) - https://plnkr.co/edit/LzKlQ8fV6L0UE8Uv

And it works ok for me. At this moment I'm working with the sample you provided to find out what is going wrong.

**Comment by tsv2013** [comment] 2020-04-28 13:34
It looks like the issue is related to the noUIslider styles and can be fixed via the following css:
```CSS
.noUi-origin {
    height: 10%;
    width: 10%;
}
```
Here is the updated sample - https://stackblitz.com/edit/surveyjs-widgets-react-zbmetj?file=style.css

**Comment by tsv2013** [comment] 2020-04-28 13:40
I've added necessary style in our code. Fix will be available in the v1.7.4.

**Comment by StevenVerbiest** [comment] 2020-04-29 08:47
Super, thanks!

**Closed** 2020-05-02 05:30 UTC
Labels: bug, fixed
