### ISSUE TITLE
Bootstrap Datepicker not available

### ISSUE THREAD

**Issue by willgdjones** [surveyjs/widgets#96] opened 2018-12-11 10:28 UTC
### Are you requesting a feature, reporting a bug or asking a question?
Requesting a feature

### What is the current behavior?
I would like to use the Bootstrap Datepicker, which seems to be available in the widgets src.
https://github.com/surveyjs/widgets/tree/master/src

### What is the expected behavior?
I can't seem to be able to import the bootstrap datepicker in the Survey Editor with e.g.

```
widgets.bootstrapdatepicker(SurveyKo);
```

It seems like it is not exported in the https://github.com/surveyjs/widgets/blob/master/webpack.config.js file - so should be a straightforward fix.

**Comment by dmitrykurmanov** [comment] 2018-12-12 09:07
duplicate of https://github.com/surveyjs/widgets/issues/95

**Closed by dmitrykurmanov** 2018-12-12 09:07 UTC
