### ISSUE TITLE
Ability to configure the sortablejs styling

### ISSUE THREAD

**Issue by Martin-Milsom** [surveyjs/widgets#73] opened 2018-08-13 08:57 UTC
I want to be able to the change the styling on the sortablejs widget. To do so, I'd want to add a css class to the source and destination boxes. We could add in some general config that could be extended for the widget.

```
if (survey.sortablejsConfig.destinationClassName) {
       resultEl.className = survey.sortablejsConfig.destinationClassName;
}

if (survey.sortablejsConfig.sourceClassName) {
       sourceEl.className = survey.sortablejsConfig.sourceClassName;
 }

```

and taking this further, we could also provide:
```
areaStyle: survey.sortablejsConfig.areaStyle ? survey.sortablejsConfig.areaStyle : "border: 1px solid #1ab394; width:100%; min-height:50px"

itemStyle: survey.sortablejsConfig.itemStyle ? survey.sortablejsConfig.itemStyle : "background-color:#1ab394;color:#fff;margin:5px;padding:10px;"
```

**Comment by dmitrykurmanov** [comment] 2018-08-13 12:10
duplicate of https://github.com/surveyjs/surveyjs/issues/1271

**Comment by dmitrykurmanov** [comment] 2018-08-13 14:30
@Martin-Milsom, @ChrisAldridgeRIT, I've added css classes for the widget: 
```css
.sjs-sortablejs-root {}
.sjs-sortablejs-result {}
.sjs-sortablejs-source {}
.sjs-sortablejs-item {}
```

and I've added the `useCustomTheme` (default equals `true`) option. So now you can set it to `false` and use css classes. Here an example:
https://plnkr.co/edit/rGY3ElJS9oATdALKvMzS?p=preview

Fix will be available in the next minor update.

**Closed by dmitrykurmanov** 2018-08-13 14:30 UTC
Labels: enhancement
